// Mocks generated by Mockito 5.4.6 from annotations
// in memory_palace/test/backup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:memory_palace/models/objectbox_models.dart' as _i5;
import 'package:memory_palace/models/types.dart' as _i2;
import 'package:memory_palace/services/storage_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserSettings_0 extends _i1.SmartFake implements _i2.UserSettings {
  _FakeUserSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  @override
  _i4.Future<List<_i2.JournalEntry>> getJournal() => (super.noSuchMethod(
        Invocation.method(
          #getJournal,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.JournalEntry>>.value(<_i2.JournalEntry>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.JournalEntry>>.value(<_i2.JournalEntry>[]),
      ) as _i4.Future<List<_i2.JournalEntry>>);

  @override
  _i4.Future<void> saveJournalEntry(_i2.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJournalEntry,
          [entry],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteJournalEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJournalEntry,
          [entryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.ObjectBoxJournalEntry?> getJournalEntryById(String? entryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJournalEntryById,
          [entryId],
        ),
        returnValue: _i4.Future<_i5.ObjectBoxJournalEntry?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i5.ObjectBoxJournalEntry?>.value(),
      ) as _i4.Future<_i5.ObjectBoxJournalEntry?>);

  @override
  _i4.Future<List<_i2.RankingCategory>> getFavoriteRankings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteRankings,
          [],
        ),
        returnValue: _i4.Future<List<_i2.RankingCategory>>.value(
            <_i2.RankingCategory>[]),
        returnValueForMissingStub: _i4.Future<List<_i2.RankingCategory>>.value(
            <_i2.RankingCategory>[]),
      ) as _i4.Future<List<_i2.RankingCategory>>);

  @override
  _i4.Future<List<_i2.RankingCategory>> getRankings() => (super.noSuchMethod(
        Invocation.method(
          #getRankings,
          [],
        ),
        returnValue: _i4.Future<List<_i2.RankingCategory>>.value(
            <_i2.RankingCategory>[]),
        returnValueForMissingStub: _i4.Future<List<_i2.RankingCategory>>.value(
            <_i2.RankingCategory>[]),
      ) as _i4.Future<List<_i2.RankingCategory>>);

  @override
  _i4.Future<void> addRankingCategory(_i2.RankingCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRankingCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRankingCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRankingCategory,
          [categoryId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRankingCategory(_i2.RankingCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRankingCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addRankedItem(
    String? categoryId,
    _i2.RankedItem? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRankedItem,
          [
            categoryId,
            item,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRankedItem(
    String? categoryId,
    String? itemId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRankedItem,
          [
            categoryId,
            itemId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reorderRankedItems(
    String? categoryId,
    List<_i2.RankedItem>? reordered,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderRankedItems,
          [
            categoryId,
            reordered,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.UserSettings getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _FakeUserSettings_0(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUserSettings_0(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        ),
      ) as _i2.UserSettings);

  @override
  _i4.Future<_i2.UserSettings> saveSettings(_i2.UserSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [settings],
        ),
        returnValue: _i4.Future<_i2.UserSettings>.value(_FakeUserSettings_0(
          this,
          Invocation.method(
            #saveSettings,
            [settings],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UserSettings>.value(_FakeUserSettings_0(
          this,
          Invocation.method(
            #saveSettings,
            [settings],
          ),
        )),
      ) as _i4.Future<_i2.UserSettings>);

  @override
  _i4.Future<void> saveDraft(
    String? draftId,
    String? draftData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDraft,
          [
            draftId,
            draftData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getDraft(String? draftId) => (super.noSuchMethod(
        Invocation.method(
          #getDraft,
          [draftId],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteDraft(String? draftId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDraft,
          [draftId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getAllDraftIds() => (super.noSuchMethod(
        Invocation.method(
          #getAllDraftIds,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> clearAllDrafts() => (super.noSuchMethod(
        Invocation.method(
          #clearAllDrafts,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
