// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5355389132980470044),
    name: 'ObjectBoxJournalEntry',
    lastPropertyId: const obx_int.IdUid(13, 4052695605142418),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4684914761854019077),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8730714886835136593),
        name: 'entryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5740934757078436138),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4465200376036976307),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8565994311446156958),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1561532316272631982),
        name: 'headline',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5485791130699113816),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2324580444866125618),
        name: 'moodIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5085627330885771627),
        name: 'feeling',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2332189112512009919),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5700543217878334000),
        name: 'locationJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4548562381437189970),
        name: 'timeBucketIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 453157595069522278),
        name: 'imagesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4052695605142418),
        name: 'isSpotlight',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6201097887440269210),
    name: 'ObjectBoxRankingCategory',
    lastPropertyId: const obx_int.IdUid(6, 4134302183630457136),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7686904465318570063),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2767786116500704473),
        name: 'categoryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 226733456472232181),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6203828788090296218),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1522372711590917237),
        name: 'iconName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5506695917038589590),
        name: 'itemsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4134302183630457136),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3031694957752151615),
    name: 'ObjectBoxUserSettings',
    lastPropertyId: const obx_int.IdUid(4, 2538070599981820752),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 889611574458153561),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8613753699710777479),
        name: 'securityEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4220236750062507041),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2538070599981820752),
        name: 'theme',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3585901973835889874),
    name: 'ObjectBoxEmbeddingJob',
    lastPropertyId: const obx_int.IdUid(8, 509789025720057401),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1117379515218973791),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3556872439417552466),
        name: 'jobKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 3001375219029302713),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4189005047439268110),
        name: 'entryId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8551531285995295237),
        name: 'opType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2364649399267191259),
        name: 'attempts',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8227048881256491829),
        name: 'lastError',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8487461759383572385),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 509789025720057401),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7733320435101555191),
    name: 'ObjectBoxJournalChunk',
    lastPropertyId: const obx_int.IdUid(9, 8942645322932569868),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2646373858487337960),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7870407646578146866),
        name: 'chunkId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 214616834619001268),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3863920216845296392),
        name: 'entryId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 3288082502696320167),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5453253298598396387),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9089136160744572825),
        name: 'tokenEstimate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5504773770273968173),
        name: 'chunkText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8100802078076063927),
        name: 'embeddingModelId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8046139973925328996),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(6, 6377407347351135660),
        hnswParams: obx_int.ModelHnswParams(
          dimensions: 768,
          distanceType: 2,
          vectorCacheHintSizeKB: 262144,
        ),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8942645322932569868),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7768885777799461887),
    name: 'ObjectBoxAiModel',
    lastPropertyId: const obx_int.IdUid(12, 208442891367359287),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5626053791981755690),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 160929985795630056),
        name: 'modelId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(7, 5688953762199169554),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6773261238535694010),
        name: 'roleIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 894183330041035915),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8473006516861928416),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3340722014534506153),
        name: 'checksum',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4809184213554774813),
        name: 'fileSizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5532172256105894910),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7147759024845429765),
        name: 'isUsable',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1989601987455538914),
        name: 'lastError',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7632437575392646137),
        name: 'importedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 208442891367359287),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 145200524995731987),
    name: 'ObjectBoxAiRuntimeConfig',
    lastPropertyId: const obx_int.IdUid(11, 3935307197206660791),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7081238748852946730),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5907227477452697104),
        name: 'backendIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1605566635441964067),
        name: 'autoPolicy',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3313504787204248815),
        name: 'pauseEmbeddingOnLowBattery',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2354817060094348971),
        name: 'lowBatteryThreshold',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2007564073376562653),
        name: 'forcedContextSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8941261146730272033),
        name: 'forcedThreads',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 235111832187678466),
        name: 'forcedGpuLayers',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6143100621495716399),
        name: 'maxGenerationTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1598783131671612557),
        name: 'chatEngineIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3935307197206660791),
        name: 'aicoreAutoDownload',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 145200524995731987),
    lastIndexId: const obx_int.IdUid(7, 5688953762199169554),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ObjectBoxJournalEntry: obx_int.EntityDefinition<ObjectBoxJournalEntry>(
      model: _entities[0],
      toOneRelations: (ObjectBoxJournalEntry object) => [],
      toManyRelations: (ObjectBoxJournalEntry object) => {},
      getId: (ObjectBoxJournalEntry object) => object.id,
      setId: (ObjectBoxJournalEntry object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxJournalEntry object, fb.Builder fbb) {
        final entryIdOffset = fbb.writeString(object.entryId);
        final headlineOffset = fbb.writeString(object.headline);
        final contentOffset = fbb.writeString(object.content);
        final feelingOffset =
            object.feeling == null ? null : fbb.writeString(object.feeling!);
        final tagsJsonOffset = fbb.writeString(object.tagsJson);
        final locationJsonOffset = object.locationJson == null
            ? null
            : fbb.writeString(object.locationJson!);
        final imagesJsonOffset = fbb.writeString(object.imagesJson);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entryIdOffset);
        fbb.addInt64(2, object.typeIndex);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addOffset(4, headlineOffset);
        fbb.addOffset(5, contentOffset);
        fbb.addInt64(6, object.moodIndex);
        fbb.addOffset(7, feelingOffset);
        fbb.addOffset(8, tagsJsonOffset);
        fbb.addOffset(9, locationJsonOffset);
        fbb.addInt64(10, object.timeBucketIndex);
        fbb.addOffset(11, imagesJsonOffset);
        fbb.addBool(12, object.isSpotlight);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxJournalEntry()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..entryId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..typeIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          )
          ..headline = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..content = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..moodIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..feeling = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 18)
          ..tagsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..locationJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..timeBucketIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..imagesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..isSpotlight = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          );

        return object;
      },
    ),
    ObjectBoxRankingCategory:
        obx_int.EntityDefinition<ObjectBoxRankingCategory>(
      model: _entities[1],
      toOneRelations: (ObjectBoxRankingCategory object) => [],
      toManyRelations: (ObjectBoxRankingCategory object) => {},
      getId: (ObjectBoxRankingCategory object) => object.id,
      setId: (ObjectBoxRankingCategory object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxRankingCategory object, fb.Builder fbb) {
        final categoryIdOffset = fbb.writeString(object.categoryId);
        final titleOffset = fbb.writeString(object.title);
        final iconNameOffset = fbb.writeString(object.iconName);
        final itemsJsonOffset = fbb.writeString(object.itemsJson);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, categoryIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, iconNameOffset);
        fbb.addOffset(4, itemsJsonOffset);
        fbb.addBool(5, object.isFavorite);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxRankingCategory()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..categoryId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..title = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..iconName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..itemsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..isFavorite = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          );

        return object;
      },
    ),
    ObjectBoxUserSettings: obx_int.EntityDefinition<ObjectBoxUserSettings>(
      model: _entities[2],
      toOneRelations: (ObjectBoxUserSettings object) => [],
      toManyRelations: (ObjectBoxUserSettings object) => {},
      getId: (ObjectBoxUserSettings object) => object.id,
      setId: (ObjectBoxUserSettings object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxUserSettings object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        final themeOffset = fbb.writeString(object.theme);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.securityEnabled);
        fbb.addOffset(2, usernameOffset);
        fbb.addOffset(3, themeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxUserSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..securityEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            6,
            false,
          )
          ..username = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..theme = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '');

        return object;
      },
    ),
    ObjectBoxEmbeddingJob: obx_int.EntityDefinition<ObjectBoxEmbeddingJob>(
      model: _entities[3],
      toOneRelations: (ObjectBoxEmbeddingJob object) => [],
      toManyRelations: (ObjectBoxEmbeddingJob object) => {},
      getId: (ObjectBoxEmbeddingJob object) => object.id,
      setId: (ObjectBoxEmbeddingJob object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxEmbeddingJob object, fb.Builder fbb) {
        final jobKeyOffset = fbb.writeString(object.jobKey);
        final entryIdOffset = fbb.writeString(object.entryId);
        final lastErrorOffset = object.lastError == null
            ? null
            : fbb.writeString(object.lastError!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, jobKeyOffset);
        fbb.addOffset(2, entryIdOffset);
        fbb.addInt64(3, object.opType);
        fbb.addInt64(4, object.attempts);
        fbb.addOffset(5, lastErrorOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxEmbeddingJob()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..jobKey = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..entryId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..opType = const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
          ..attempts = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..lastError = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          );

        return object;
      },
    ),
    ObjectBoxJournalChunk: obx_int.EntityDefinition<ObjectBoxJournalChunk>(
      model: _entities[4],
      toOneRelations: (ObjectBoxJournalChunk object) => [],
      toManyRelations: (ObjectBoxJournalChunk object) => {},
      getId: (ObjectBoxJournalChunk object) => object.id,
      setId: (ObjectBoxJournalChunk object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxJournalChunk object, fb.Builder fbb) {
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final entryIdOffset = fbb.writeString(object.entryId);
        final chunkTextOffset = fbb.writeString(object.chunkText);
        final embeddingModelIdOffset = fbb.writeString(object.embeddingModelId);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, chunkIdOffset);
        fbb.addOffset(2, entryIdOffset);
        fbb.addInt64(3, object.chunkIndex);
        fbb.addInt64(4, object.tokenEstimate);
        fbb.addOffset(5, chunkTextOffset);
        fbb.addOffset(6, embeddingModelIdOffset);
        fbb.addOffset(7, embeddingOffset);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxJournalChunk()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..chunkId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..entryId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..chunkIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..tokenEstimate = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..chunkText = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..embeddingModelId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..embedding = const fb.ListReader<double>(
            fb.Float32Reader(),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 18, [])
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          );

        return object;
      },
    ),
    ObjectBoxAiModel: obx_int.EntityDefinition<ObjectBoxAiModel>(
      model: _entities[5],
      toOneRelations: (ObjectBoxAiModel object) => [],
      toManyRelations: (ObjectBoxAiModel object) => {},
      getId: (ObjectBoxAiModel object) => object.id,
      setId: (ObjectBoxAiModel object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxAiModel object, fb.Builder fbb) {
        final modelIdOffset = fbb.writeString(object.modelId);
        final displayNameOffset = fbb.writeString(object.displayName);
        final filePathOffset = fbb.writeString(object.filePath);
        final checksumOffset = fbb.writeString(object.checksum);
        final lastErrorOffset = object.lastError == null
            ? null
            : fbb.writeString(object.lastError!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, modelIdOffset);
        fbb.addInt64(2, object.roleIndex);
        fbb.addOffset(3, displayNameOffset);
        fbb.addOffset(4, filePathOffset);
        fbb.addOffset(5, checksumOffset);
        fbb.addInt64(6, object.fileSizeBytes);
        fbb.addBool(7, object.isActive);
        fbb.addBool(8, object.isUsable);
        fbb.addOffset(9, lastErrorOffset);
        fbb.addInt64(10, object.importedAt.millisecondsSinceEpoch);
        fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxAiModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..modelId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..roleIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..displayName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..filePath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..checksum = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..fileSizeBytes = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..isUsable = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..lastError = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..importedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
          );

        return object;
      },
    ),
    ObjectBoxAiRuntimeConfig:
        obx_int.EntityDefinition<ObjectBoxAiRuntimeConfig>(
      model: _entities[6],
      toOneRelations: (ObjectBoxAiRuntimeConfig object) => [],
      toManyRelations: (ObjectBoxAiRuntimeConfig object) => {},
      getId: (ObjectBoxAiRuntimeConfig object) => object.id,
      setId: (ObjectBoxAiRuntimeConfig object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxAiRuntimeConfig object, fb.Builder fbb) {
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.backendIndex);
        fbb.addBool(2, object.autoPolicy);
        fbb.addBool(3, object.pauseEmbeddingOnLowBattery);
        fbb.addInt64(4, object.lowBatteryThreshold);
        fbb.addInt64(5, object.forcedContextSize);
        fbb.addInt64(6, object.forcedThreads);
        fbb.addInt64(7, object.forcedGpuLayers);
        fbb.addInt64(8, object.maxGenerationTokens);
        fbb.addInt64(9, object.chatEngineIndex);
        fbb.addBool(10, object.aicoreAutoDownload);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxAiRuntimeConfig()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..backendIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..autoPolicy = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            8,
            false,
          )
          ..pauseEmbeddingOnLowBattery = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..lowBatteryThreshold = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..forcedContextSize = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..forcedThreads = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..forcedGpuLayers = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..maxGenerationTokens = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..chatEngineIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..aicoreAutoDownload = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            24,
            false,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ObjectBoxJournalEntry] entity fields to define ObjectBox queries.
class ObjectBoxJournalEntry_ {
  /// See [ObjectBoxJournalEntry.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[0],
  );

  /// See [ObjectBoxJournalEntry.entryId].
  static final entryId = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[1],
  );

  /// See [ObjectBoxJournalEntry.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[2],
  );

  /// See [ObjectBoxJournalEntry.date].
  static final date = obx.QueryDateProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[3],
  );

  /// See [ObjectBoxJournalEntry.headline].
  static final headline = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[4],
  );

  /// See [ObjectBoxJournalEntry.content].
  static final content = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[5],
  );

  /// See [ObjectBoxJournalEntry.moodIndex].
  static final moodIndex = obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[6],
  );

  /// See [ObjectBoxJournalEntry.feeling].
  static final feeling = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[7],
  );

  /// See [ObjectBoxJournalEntry.tagsJson].
  static final tagsJson = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[8],
  );

  /// See [ObjectBoxJournalEntry.locationJson].
  static final locationJson = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[9],
  );

  /// See [ObjectBoxJournalEntry.timeBucketIndex].
  static final timeBucketIndex =
      obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[10],
  );

  /// See [ObjectBoxJournalEntry.imagesJson].
  static final imagesJson = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[11],
  );

  /// See [ObjectBoxJournalEntry.isSpotlight].
  static final isSpotlight = obx.QueryBooleanProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[12],
  );
}

/// [ObjectBoxRankingCategory] entity fields to define ObjectBox queries.
class ObjectBoxRankingCategory_ {
  /// See [ObjectBoxRankingCategory.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[0],
  );

  /// See [ObjectBoxRankingCategory.categoryId].
  static final categoryId = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[1],
  );

  /// See [ObjectBoxRankingCategory.title].
  static final title = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[2],
  );

  /// See [ObjectBoxRankingCategory.iconName].
  static final iconName = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[3],
  );

  /// See [ObjectBoxRankingCategory.itemsJson].
  static final itemsJson = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[4],
  );

  /// See [ObjectBoxRankingCategory.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[5],
  );
}

/// [ObjectBoxUserSettings] entity fields to define ObjectBox queries.
class ObjectBoxUserSettings_ {
  /// See [ObjectBoxUserSettings.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxUserSettings>(
    _entities[2].properties[0],
  );

  /// See [ObjectBoxUserSettings.securityEnabled].
  static final securityEnabled =
      obx.QueryBooleanProperty<ObjectBoxUserSettings>(
    _entities[2].properties[1],
  );

  /// See [ObjectBoxUserSettings.username].
  static final username = obx.QueryStringProperty<ObjectBoxUserSettings>(
    _entities[2].properties[2],
  );

  /// See [ObjectBoxUserSettings.theme].
  static final theme = obx.QueryStringProperty<ObjectBoxUserSettings>(
    _entities[2].properties[3],
  );
}

/// [ObjectBoxEmbeddingJob] entity fields to define ObjectBox queries.
class ObjectBoxEmbeddingJob_ {
  /// See [ObjectBoxEmbeddingJob.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[0],
  );

  /// See [ObjectBoxEmbeddingJob.jobKey].
  static final jobKey = obx.QueryStringProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[1],
  );

  /// See [ObjectBoxEmbeddingJob.entryId].
  static final entryId = obx.QueryStringProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[2],
  );

  /// See [ObjectBoxEmbeddingJob.opType].
  static final opType = obx.QueryIntegerProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[3],
  );

  /// See [ObjectBoxEmbeddingJob.attempts].
  static final attempts = obx.QueryIntegerProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[4],
  );

  /// See [ObjectBoxEmbeddingJob.lastError].
  static final lastError = obx.QueryStringProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[5],
  );

  /// See [ObjectBoxEmbeddingJob.createdAt].
  static final createdAt = obx.QueryDateProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[6],
  );

  /// See [ObjectBoxEmbeddingJob.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ObjectBoxEmbeddingJob>(
    _entities[3].properties[7],
  );
}

/// [ObjectBoxJournalChunk] entity fields to define ObjectBox queries.
class ObjectBoxJournalChunk_ {
  /// See [ObjectBoxJournalChunk.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[0],
  );

  /// See [ObjectBoxJournalChunk.chunkId].
  static final chunkId = obx.QueryStringProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[1],
  );

  /// See [ObjectBoxJournalChunk.entryId].
  static final entryId = obx.QueryStringProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[2],
  );

  /// See [ObjectBoxJournalChunk.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[3],
  );

  /// See [ObjectBoxJournalChunk.tokenEstimate].
  static final tokenEstimate = obx.QueryIntegerProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[4],
  );

  /// See [ObjectBoxJournalChunk.chunkText].
  static final chunkText = obx.QueryStringProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[5],
  );

  /// See [ObjectBoxJournalChunk.embeddingModelId].
  static final embeddingModelId =
      obx.QueryStringProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[6],
  );

  /// See [ObjectBoxJournalChunk.embedding].
  static final embedding = obx.QueryHnswProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[7],
  );

  /// See [ObjectBoxJournalChunk.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ObjectBoxJournalChunk>(
    _entities[4].properties[8],
  );
}

/// [ObjectBoxAiModel] entity fields to define ObjectBox queries.
class ObjectBoxAiModel_ {
  /// See [ObjectBoxAiModel.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxAiModel>(
    _entities[5].properties[0],
  );

  /// See [ObjectBoxAiModel.modelId].
  static final modelId = obx.QueryStringProperty<ObjectBoxAiModel>(
    _entities[5].properties[1],
  );

  /// See [ObjectBoxAiModel.roleIndex].
  static final roleIndex = obx.QueryIntegerProperty<ObjectBoxAiModel>(
    _entities[5].properties[2],
  );

  /// See [ObjectBoxAiModel.displayName].
  static final displayName = obx.QueryStringProperty<ObjectBoxAiModel>(
    _entities[5].properties[3],
  );

  /// See [ObjectBoxAiModel.filePath].
  static final filePath = obx.QueryStringProperty<ObjectBoxAiModel>(
    _entities[5].properties[4],
  );

  /// See [ObjectBoxAiModel.checksum].
  static final checksum = obx.QueryStringProperty<ObjectBoxAiModel>(
    _entities[5].properties[5],
  );

  /// See [ObjectBoxAiModel.fileSizeBytes].
  static final fileSizeBytes = obx.QueryIntegerProperty<ObjectBoxAiModel>(
    _entities[5].properties[6],
  );

  /// See [ObjectBoxAiModel.isActive].
  static final isActive = obx.QueryBooleanProperty<ObjectBoxAiModel>(
    _entities[5].properties[7],
  );

  /// See [ObjectBoxAiModel.isUsable].
  static final isUsable = obx.QueryBooleanProperty<ObjectBoxAiModel>(
    _entities[5].properties[8],
  );

  /// See [ObjectBoxAiModel.lastError].
  static final lastError = obx.QueryStringProperty<ObjectBoxAiModel>(
    _entities[5].properties[9],
  );

  /// See [ObjectBoxAiModel.importedAt].
  static final importedAt = obx.QueryDateProperty<ObjectBoxAiModel>(
    _entities[5].properties[10],
  );

  /// See [ObjectBoxAiModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ObjectBoxAiModel>(
    _entities[5].properties[11],
  );
}

/// [ObjectBoxAiRuntimeConfig] entity fields to define ObjectBox queries.
class ObjectBoxAiRuntimeConfig_ {
  /// See [ObjectBoxAiRuntimeConfig.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[0],
  );

  /// See [ObjectBoxAiRuntimeConfig.backendIndex].
  static final backendIndex =
      obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[1],
  );

  /// See [ObjectBoxAiRuntimeConfig.autoPolicy].
  static final autoPolicy = obx.QueryBooleanProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[2],
  );

  /// See [ObjectBoxAiRuntimeConfig.pauseEmbeddingOnLowBattery].
  static final pauseEmbeddingOnLowBattery =
      obx.QueryBooleanProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[3],
  );

  /// See [ObjectBoxAiRuntimeConfig.lowBatteryThreshold].
  static final lowBatteryThreshold =
      obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[4],
  );

  /// See [ObjectBoxAiRuntimeConfig.forcedContextSize].
  static final forcedContextSize =
      obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[5],
  );

  /// See [ObjectBoxAiRuntimeConfig.forcedThreads].
  static final forcedThreads =
      obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[6],
  );

  /// See [ObjectBoxAiRuntimeConfig.forcedGpuLayers].
  static final forcedGpuLayers =
      obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[7],
  );

  /// See [ObjectBoxAiRuntimeConfig.maxGenerationTokens].
  static final maxGenerationTokens =
      obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[8],
  );

  /// See [ObjectBoxAiRuntimeConfig.chatEngineIndex].
  static final chatEngineIndex =
      obx.QueryIntegerProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[9],
  );

  /// See [ObjectBoxAiRuntimeConfig.aicoreAutoDownload].
  static final aicoreAutoDownload =
      obx.QueryBooleanProperty<ObjectBoxAiRuntimeConfig>(
    _entities[6].properties[10],
  );
}
