// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5355389132980470044),
    name: 'ObjectBoxJournalEntry',
    lastPropertyId: const obx_int.IdUid(13, 4052695605142418),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4684914761854019077),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8730714886835136593),
        name: 'entryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5740934757078436138),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4465200376036976307),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8565994311446156958),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1561532316272631982),
        name: 'headline',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5485791130699113816),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2324580444866125618),
        name: 'moodIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5085627330885771627),
        name: 'feeling',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2332189112512009919),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5700543217878334000),
        name: 'locationJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4548562381437189970),
        name: 'timeBucketIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 453157595069522278),
        name: 'imagesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4052695605142418),
        name: 'isSpotlight',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6201097887440269210),
    name: 'ObjectBoxRankingCategory',
    lastPropertyId: const obx_int.IdUid(6, 4134302183630457136),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7686904465318570063),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2767786116500704473),
        name: 'categoryId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 226733456472232181),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6203828788090296218),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1522372711590917237),
        name: 'iconName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5506695917038589590),
        name: 'itemsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4134302183630457136),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3031694957752151615),
    name: 'ObjectBoxUserSettings',
    lastPropertyId: const obx_int.IdUid(4, 2538070599981820752),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 889611574458153561),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8613753699710777479),
        name: 'securityEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4220236750062507041),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2538070599981820752),
        name: 'theme',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 3031694957752151615),
    lastIndexId: const obx_int.IdUid(2, 226733456472232181),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ObjectBoxJournalEntry: obx_int.EntityDefinition<ObjectBoxJournalEntry>(
      model: _entities[0],
      toOneRelations: (ObjectBoxJournalEntry object) => [],
      toManyRelations: (ObjectBoxJournalEntry object) => {},
      getId: (ObjectBoxJournalEntry object) => object.id,
      setId: (ObjectBoxJournalEntry object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxJournalEntry object, fb.Builder fbb) {
        final entryIdOffset = fbb.writeString(object.entryId);
        final headlineOffset = fbb.writeString(object.headline);
        final contentOffset = fbb.writeString(object.content);
        final feelingOffset = object.feeling == null
            ? null
            : fbb.writeString(object.feeling!);
        final tagsJsonOffset = fbb.writeString(object.tagsJson);
        final locationJsonOffset = object.locationJson == null
            ? null
            : fbb.writeString(object.locationJson!);
        final imagesJsonOffset = fbb.writeString(object.imagesJson);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entryIdOffset);
        fbb.addInt64(2, object.typeIndex);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.addOffset(4, headlineOffset);
        fbb.addOffset(5, contentOffset);
        fbb.addInt64(6, object.moodIndex);
        fbb.addOffset(7, feelingOffset);
        fbb.addOffset(8, tagsJsonOffset);
        fbb.addOffset(9, locationJsonOffset);
        fbb.addInt64(10, object.timeBucketIndex);
        fbb.addOffset(11, imagesJsonOffset);
        fbb.addBool(12, object.isSpotlight);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxJournalEntry()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..entryId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..typeIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          )
          ..headline = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..content = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..moodIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..feeling = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 18)
          ..tagsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..locationJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..timeBucketIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          )
          ..imagesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..isSpotlight = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          );

        return object;
      },
    ),
    ObjectBoxRankingCategory:
        obx_int.EntityDefinition<ObjectBoxRankingCategory>(
          model: _entities[1],
          toOneRelations: (ObjectBoxRankingCategory object) => [],
          toManyRelations: (ObjectBoxRankingCategory object) => {},
          getId: (ObjectBoxRankingCategory object) => object.id,
          setId: (ObjectBoxRankingCategory object, int id) {
            object.id = id;
          },
          objectToFB: (ObjectBoxRankingCategory object, fb.Builder fbb) {
            final categoryIdOffset = fbb.writeString(object.categoryId);
            final titleOffset = fbb.writeString(object.title);
            final iconNameOffset = fbb.writeString(object.iconName);
            final itemsJsonOffset = fbb.writeString(object.itemsJson);
            fbb.startTable(7);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, categoryIdOffset);
            fbb.addOffset(2, titleOffset);
            fbb.addOffset(3, iconNameOffset);
            fbb.addOffset(4, itemsJsonOffset);
            fbb.addBool(5, object.isFavorite);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);

            final object = ObjectBoxRankingCategory()
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..categoryId = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 6, '')
              ..title = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 8, '')
              ..iconName = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 10, '')
              ..itemsJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 12, '')
              ..isFavorite = const fb.BoolReader().vTableGet(
                buffer,
                rootOffset,
                14,
                false,
              );

            return object;
          },
        ),
    ObjectBoxUserSettings: obx_int.EntityDefinition<ObjectBoxUserSettings>(
      model: _entities[2],
      toOneRelations: (ObjectBoxUserSettings object) => [],
      toManyRelations: (ObjectBoxUserSettings object) => {},
      getId: (ObjectBoxUserSettings object) => object.id,
      setId: (ObjectBoxUserSettings object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxUserSettings object, fb.Builder fbb) {
        final usernameOffset = fbb.writeString(object.username);
        final themeOffset = fbb.writeString(object.theme);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.securityEnabled);
        fbb.addOffset(2, usernameOffset);
        fbb.addOffset(3, themeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ObjectBoxUserSettings()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..securityEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            6,
            false,
          )
          ..username = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..theme = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ObjectBoxJournalEntry] entity fields to define ObjectBox queries.
class ObjectBoxJournalEntry_ {
  /// See [ObjectBoxJournalEntry.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[0],
  );

  /// See [ObjectBoxJournalEntry.entryId].
  static final entryId = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[1],
  );

  /// See [ObjectBoxJournalEntry.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[2],
  );

  /// See [ObjectBoxJournalEntry.date].
  static final date = obx.QueryDateProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[3],
  );

  /// See [ObjectBoxJournalEntry.headline].
  static final headline = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[4],
  );

  /// See [ObjectBoxJournalEntry.content].
  static final content = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[5],
  );

  /// See [ObjectBoxJournalEntry.moodIndex].
  static final moodIndex = obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[6],
  );

  /// See [ObjectBoxJournalEntry.feeling].
  static final feeling = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[7],
  );

  /// See [ObjectBoxJournalEntry.tagsJson].
  static final tagsJson = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[8],
  );

  /// See [ObjectBoxJournalEntry.locationJson].
  static final locationJson = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[9],
  );

  /// See [ObjectBoxJournalEntry.timeBucketIndex].
  static final timeBucketIndex =
      obx.QueryIntegerProperty<ObjectBoxJournalEntry>(
        _entities[0].properties[10],
      );

  /// See [ObjectBoxJournalEntry.imagesJson].
  static final imagesJson = obx.QueryStringProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[11],
  );

  /// See [ObjectBoxJournalEntry.isSpotlight].
  static final isSpotlight = obx.QueryBooleanProperty<ObjectBoxJournalEntry>(
    _entities[0].properties[12],
  );
}

/// [ObjectBoxRankingCategory] entity fields to define ObjectBox queries.
class ObjectBoxRankingCategory_ {
  /// See [ObjectBoxRankingCategory.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[0],
  );

  /// See [ObjectBoxRankingCategory.categoryId].
  static final categoryId = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[1],
  );

  /// See [ObjectBoxRankingCategory.title].
  static final title = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[2],
  );

  /// See [ObjectBoxRankingCategory.iconName].
  static final iconName = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[3],
  );

  /// See [ObjectBoxRankingCategory.itemsJson].
  static final itemsJson = obx.QueryStringProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[4],
  );

  /// See [ObjectBoxRankingCategory.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<ObjectBoxRankingCategory>(
    _entities[1].properties[5],
  );
}

/// [ObjectBoxUserSettings] entity fields to define ObjectBox queries.
class ObjectBoxUserSettings_ {
  /// See [ObjectBoxUserSettings.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxUserSettings>(
    _entities[2].properties[0],
  );

  /// See [ObjectBoxUserSettings.securityEnabled].
  static final securityEnabled =
      obx.QueryBooleanProperty<ObjectBoxUserSettings>(
        _entities[2].properties[1],
      );

  /// See [ObjectBoxUserSettings.username].
  static final username = obx.QueryStringProperty<ObjectBoxUserSettings>(
    _entities[2].properties[2],
  );

  /// See [ObjectBoxUserSettings.theme].
  static final theme = obx.QueryStringProperty<ObjectBoxUserSettings>(
    _entities[2].properties[3],
  );
}
