// Mocks generated by Mockito 5.4.6 from annotations
// in memory_palace/test/widget/root_orchestrator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter/foundation.dart' as _i8;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:memory_palace/models/objectbox_models.dart' as _i7;
import 'package:memory_palace/models/paged_result.dart' as _i2;
import 'package:memory_palace/models/types.dart' as _i3;
import 'package:memory_palace/services/storage_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePagedResult_0<T> extends _i1.SmartFake
    implements _i2.PagedResult<T> {
  _FakePagedResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVisionBoard_1 extends _i1.SmartFake implements _i3.VisionBoard {
  _FakeVisionBoard_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserSettings_2 extends _i1.SmartFake implements _i3.UserSettings {
  _FakeUserSettings_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_3 extends _i1.SmartFake implements _i4.IOSOptions {
  _FakeIOSOptions_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_4 extends _i1.SmartFake
    implements _i4.AndroidOptions {
  _FakeAndroidOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_5 extends _i1.SmartFake implements _i4.LinuxOptions {
  _FakeLinuxOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_6 extends _i1.SmartFake
    implements _i4.WindowsOptions {
  _FakeWindowsOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_7 extends _i1.SmartFake implements _i4.WebOptions {
  _FakeWebOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppleOptions_8 extends _i1.SmartFake implements _i4.AppleOptions {
  _FakeAppleOptions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i5.StorageService {
  @override
  _i6.Future<List<_i3.JournalEntry>> getJournal(
          {_i5.PrivacyFilter? privacy = _i5.PrivacyFilter.excludePrivate}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJournal,
          [],
          {#privacy: privacy},
        ),
        returnValue:
            _i6.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i6.Future<List<_i3.JournalEntry>>);

  @override
  int journalCount(
          {_i5.PrivacyFilter? privacy = _i5.PrivacyFilter.excludePrivate}) =>
      (super.noSuchMethod(
        Invocation.method(
          #journalCount,
          [],
          {#privacy: privacy},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.Future<void> saveJournalEntry(_i3.JournalEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJournalEntry,
          [entry],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.PagedResult<_i3.JournalEntry>> getJournalPage(
    int? pageSize, [
    _i2.PaginationCursor? cursor,
    _i5.PrivacyFilter? privacy = _i5.PrivacyFilter.excludePrivate,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJournalPage,
          [
            pageSize,
            cursor,
            privacy,
          ],
        ),
        returnValue: _i6.Future<_i2.PagedResult<_i3.JournalEntry>>.value(
            _FakePagedResult_0<_i3.JournalEntry>(
          this,
          Invocation.method(
            #getJournalPage,
            [
              pageSize,
              cursor,
              privacy,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.PagedResult<_i3.JournalEntry>>.value(
                _FakePagedResult_0<_i3.JournalEntry>(
          this,
          Invocation.method(
            #getJournalPage,
            [
              pageSize,
              cursor,
              privacy,
            ],
          ),
        )),
      ) as _i6.Future<_i2.PagedResult<_i3.JournalEntry>>);

  @override
  _i6.Future<List<_i3.JournalEntry>> getOnThisDay(DateTime? reference) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnThisDay,
          [reference],
        ),
        returnValue:
            _i6.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i6.Future<List<_i3.JournalEntry>>);

  @override
  _i6.Future<void> deleteJournalEntry(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJournalEntry,
          [entryId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.ObjectBoxJournalEntry?> getJournalEntryById(String? entryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJournalEntryById,
          [entryId],
        ),
        returnValue: _i6.Future<_i7.ObjectBoxJournalEntry?>.value(),
        returnValueForMissingStub:
            _i6.Future<_i7.ObjectBoxJournalEntry?>.value(),
      ) as _i6.Future<_i7.ObjectBoxJournalEntry?>);

  @override
  _i6.Future<int?> getObjectBoxIdForEntry(String? entryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObjectBoxIdForEntry,
          [entryId],
        ),
        returnValue: _i6.Future<int?>.value(),
        returnValueForMissingStub: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<void> putManyJournalEntries(List<_i3.JournalEntry>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #putManyJournalEntries,
          [entries],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, int>> getTagCounts() => (super.noSuchMethod(
        Invocation.method(
          #getTagCounts,
          [],
        ),
        returnValue: _i6.Future<Map<String, int>>.value(<String, int>{}),
        returnValueForMissingStub:
            _i6.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i6.Future<Map<String, int>>);

  @override
  _i6.Future<int> renameTag(
    String? from,
    String? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameTag,
          [
            from,
            to,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deleteTag(String? tag) => (super.noSuchMethod(
        Invocation.method(
          #deleteTag,
          [tag],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.RankingCategory>> getFavoriteRankings() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteRankings,
          [],
        ),
        returnValue: _i6.Future<List<_i3.RankingCategory>>.value(
            <_i3.RankingCategory>[]),
        returnValueForMissingStub: _i6.Future<List<_i3.RankingCategory>>.value(
            <_i3.RankingCategory>[]),
      ) as _i6.Future<List<_i3.RankingCategory>>);

  @override
  _i6.Future<List<_i3.RankingCategory>> getRankings() => (super.noSuchMethod(
        Invocation.method(
          #getRankings,
          [],
        ),
        returnValue: _i6.Future<List<_i3.RankingCategory>>.value(
            <_i3.RankingCategory>[]),
        returnValueForMissingStub: _i6.Future<List<_i3.RankingCategory>>.value(
            <_i3.RankingCategory>[]),
      ) as _i6.Future<List<_i3.RankingCategory>>);

  @override
  _i6.Future<void> addRankingCategory(_i3.RankingCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRankingCategory,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRankingCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRankingCategory,
          [categoryId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateRankingCategory(_i3.RankingCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRankingCategory,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addRankedItem(
    String? categoryId,
    _i3.RankedItem? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRankedItem,
          [
            categoryId,
            item,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRankedItem(
    String? categoryId,
    String? itemId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRankedItem,
          [
            categoryId,
            itemId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> reorderRankedItems(
    String? categoryId,
    List<_i3.RankedItem>? reordered,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderRankedItems,
          [
            categoryId,
            reordered,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i3.VisionBoard> getVisionBoards() => (super.noSuchMethod(
        Invocation.method(
          #getVisionBoards,
          [],
        ),
        returnValue: <_i3.VisionBoard>[],
        returnValueForMissingStub: <_i3.VisionBoard>[],
      ) as List<_i3.VisionBoard>);

  @override
  _i3.VisionBoard? getVisionBoardForYear(int? year) => (super.noSuchMethod(
        Invocation.method(
          #getVisionBoardForYear,
          [year],
        ),
        returnValueForMissingStub: null,
      ) as _i3.VisionBoard?);

  @override
  _i3.VisionBoard getOrCreateVisionBoard(int? year) => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateVisionBoard,
          [year],
        ),
        returnValue: _FakeVisionBoard_1(
          this,
          Invocation.method(
            #getOrCreateVisionBoard,
            [year],
          ),
        ),
        returnValueForMissingStub: _FakeVisionBoard_1(
          this,
          Invocation.method(
            #getOrCreateVisionBoard,
            [year],
          ),
        ),
      ) as _i3.VisionBoard);

  @override
  void saveVisionBoard(_i3.VisionBoard? board) => super.noSuchMethod(
        Invocation.method(
          #saveVisionBoard,
          [board],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addVisionBoardItem(
    int? year,
    _i3.VisionBoardItem? item,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addVisionBoardItem,
          [
            year,
            item,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateVisionBoardItem(
    int? year,
    _i3.VisionBoardItem? item,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateVisionBoardItem,
          [
            year,
            item,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteVisionBoardItem(
    int? year,
    String? itemId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #deleteVisionBoardItem,
          [
            year,
            itemId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void mergeVisionBoard(_i3.VisionBoard? imported) => super.noSuchMethod(
        Invocation.method(
          #mergeVisionBoard,
          [imported],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.UserSettings getSettings() => (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [],
        ),
        returnValue: _FakeUserSettings_2(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeUserSettings_2(
          this,
          Invocation.method(
            #getSettings,
            [],
          ),
        ),
      ) as _i3.UserSettings);

  @override
  _i6.Future<_i3.UserSettings> saveSettings(_i3.UserSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [settings],
        ),
        returnValue: _i6.Future<_i3.UserSettings>.value(_FakeUserSettings_2(
          this,
          Invocation.method(
            #saveSettings,
            [settings],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.UserSettings>.value(_FakeUserSettings_2(
          this,
          Invocation.method(
            #saveSettings,
            [settings],
          ),
        )),
      ) as _i6.Future<_i3.UserSettings>);

  @override
  _i6.Future<void> setOnThisDayDismissed(DateTime? day) => (super.noSuchMethod(
        Invocation.method(
          #setOnThisDayDismissed,
          [day],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isOnThisDayDismissed(DateTime? day) => (super.noSuchMethod(
        Invocation.method(
          #isOnThisDayDismissed,
          [day],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> saveDraft(
    String? draftId,
    String? draftData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDraft,
          [
            draftId,
            draftData,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getDraft(String? draftId) => (super.noSuchMethod(
        Invocation.method(
          #getDraft,
          [draftId],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> deleteDraft(String? draftId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDraft,
          [draftId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getAllDraftIds() => (super.noSuchMethod(
        Invocation.method(
          #getAllDraftIds,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<void> clearAllDrafts() => (super.noSuchMethod(
        Invocation.method(
          #clearAllDrafts,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i4.FlutterSecureStorage {
  @override
  _i4.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_3(
          this,
          Invocation.getter(#iOptions),
        ),
        returnValueForMissingStub: _FakeIOSOptions_3(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i4.IOSOptions);

  @override
  _i4.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_4(
          this,
          Invocation.getter(#aOptions),
        ),
        returnValueForMissingStub: _FakeAndroidOptions_4(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i4.AndroidOptions);

  @override
  _i4.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_5(
          this,
          Invocation.getter(#lOptions),
        ),
        returnValueForMissingStub: _FakeLinuxOptions_5(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i4.LinuxOptions);

  @override
  _i4.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_6(
          this,
          Invocation.getter(#wOptions),
        ),
        returnValueForMissingStub: _FakeWindowsOptions_6(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i4.WindowsOptions);

  @override
  _i4.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_7(
          this,
          Invocation.getter(#webOptions),
        ),
        returnValueForMissingStub: _FakeWebOptions_7(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i4.WebOptions);

  @override
  _i4.AppleOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeAppleOptions_8(
          this,
          Invocation.getter(#mOptions),
        ),
        returnValueForMissingStub: _FakeAppleOptions_8(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i4.AppleOptions);

  @override
  Map<String, List<_i8.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
        Invocation.getter(#getListeners),
        returnValue: <String, List<_i8.ValueChanged<String?>>>{},
        returnValueForMissingStub: <String, List<_i8.ValueChanged<String?>>>{},
      ) as Map<String, List<_i8.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i8.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i8.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> write({
    required String? key,
    required String? value,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> read({
    required String? key,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<bool> containsKey({
    required String? key,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> delete({
    required String? key,
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, String>> readAll({
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<Map<String, String>>.value(<String, String>{}),
        returnValueForMissingStub:
            _i6.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> deleteAll({
    _i4.AppleOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.AppleOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i6.Future<bool?>.value(),
        returnValueForMissingStub: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);
}
